repos:
  admintool:
    repo: CDLUC3/mrt-admin-sinatra
    image_repos:
    - mrt-admin-sinatra
  ui:
    repo: CDLUC3/mrt-dashboard
    image_repos:
    - mrt-dashboard
  store:
    repo: CDLUC3/mrt-store
    artifacts:
    - mrt-storewar
    image_repos:
    - mrt-store
  ingest:
    repo: CDLUC3/mrt-ingest
    artifacts:
    - mrt-ingestwar
    image_repos:
    - mrt-ingest
  inventory:
    repo: CDLUC3/mrt-inventory
    artifacts:
    - mrt-invwar
    image_repos:
    - mrt-inventory
  audit:
    repo: CDLUC3/mrt-audit
    artifacts:
    - mrt-auditwarpub
    image_repos:
    - mrt-audit
  replic:
    repo: CDLUC3/mrt-replic
    artifacts:
    - mrt-replicationwar
    image_repos:
    - mrt-replic
  core:
    repo: CDLUC3/mrt-core2
    artifacts:
    - mrt-core
  core-bom:
    repo: CDLUC3/mrt-core2
    artifacts:
    - mrt-reflectoring-bom
  core-parprop:
    repo: CDLUC3/mrt-core2
    artifacts:
    - mrt-parent-properties
  cloud:
    repo: CDLUC3/mrt-cloud
    artifacts:
    - mrt-openstackpub
    - mrt-cloudconf
    - mrt-s3srcpub
  zk:
    repo: CDLUC3/mrt-zk
    namespace: org.cdlib.mrt.zk
    artifacts:
    - MerrittZK

