docker: &docker
  token: 
    env: GHAPIPAT
    default: ''
ecs-dev: &dev
  token: 
    ssm: /uc3/mrt/dev/github/readonly
    default: ''
ecs-dbsnapshot:
  <<: *dev
ecs-ephemeral:
  <<: *dev

# would require cross acount access for ecr/artifact
ecs-stg:
  <<: *docker
ecs-prd:
  <<: *docker

default:
  <<: *docker
dockerlocal:
  <<: *docker
